require "daniel.options"
require "daniel.lsp"
require "daniel.autocmds"
require "daniel.keymaps"
require "daniel.plugins"
require "daniel.cmp"
require "daniel.treesitter"
require "daniel.telescope"
require "daniel.harpoon"
require "daniel.colorscheme"

